### PR TITLE
Add support for FlameGraph output

### PR DESCRIPTION
**Pull request by andreasf**
* New, optional command line parameter: -f
* If enabled, writes folded call stacks to output file, instead
  of statistics
* Use with the FlameGraph tool: https://github.com/brendangregg/FlameGraph

### CODE REVIEW

**Comment by xmo-odoo** [comment]
> The command-line mode of plop.collector is not the only one (I rarely use it myself), so the part that actually writes to a file should probably be moved to a method of Collector (instead of callers like main() reaching into stack_counts).

Maybe have the collector strictly just collect stack samples, and a different object would filter and format samples, with `—format` only configuring the latter object?

That means the collector would always collect a list of frames though (in case the formatter needs that), the default collector would be the one folding those into a counter.

**Comment by andreasf** [comment]
Good idea. What do you think of the changes?

**Comment by andreasf** [comment]
I just fixed the last commit, in case you're wondering. After a semi-failed `git reset` the diff was referring to a hidden commit and thus rather confusing.

**Comment by xmo-odoo** [comment]
@andreasf the ArgumentParser conversion should probably live in a separate PR (well played on `-m` being a switch, I would have missed that completely and tried to set up an exclusion group of some sort).

Could use a list literal for `Collector.stacks`, and maybe in a future PR look into preallocating it (after profiling) to avoid a possible list resizing in the middle of stack collection.

BTW if you initialise ArgumentParser with `formatter_class=ArgumentDefaultsHelpFormatter` it'll automatically insert the default values after the help text: https://docs.python.org/3/library/argparse.html#formatter-class

**Comment by andreasf** [comment]
You're right on all points. I thought about doing a separate PR for the argparse changes, but since the last commit is from 8 months ago, I was too lazy to split it up. People over processes ;-)

**Comment by bdarnell** [comment]
Wow, this looks great. For future reference I'd have a slight preference for separate PRs for the PEP8 changes and the move to argparse, but it's not worth splitting it up. 

The one thing I might change is actually the `-m` flag: it's intended to be like python's `-m` flag and take an argument. But in any case this is a big improvement over what was there before and going to go ahead and merge it; don't worry about changing `-m` unless you feel like it.

**Comment by andreasf** [comment]
Thanks!

**Pull request merged**
